version: '3.9'
services:
  python-app:
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "8050:8050"  # Map container port to host port
    volumes:
      - .:/app  # Mount the app directory for development
    environment:
      - PYTHONUNBUFFERED=1 # Prevent buffering in logs